//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public int FaultTypeId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ContractorId { get; set; }
        public int StatusId { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual FaultType FaultType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Status Status { get; set; }
    }
}
